src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeTeam.java, src/main/java/net/tiagofar78/prisonescape/game/Settings.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
Implement distributePlayersPerTeam function. Calculated number of officers and prisioners according to a ratio.
=> Implement distributePlayersPerTeam function

src/main/java/net/tiagofar78/prisonescape/managers/MessageManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessagesManager.java
=> Implemented MessageManager

src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
A class to get message translated.
=> Created MessageLanguageManager

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeItem.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/MetalDetector.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
=> Add logic for metal detectors

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Finished.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Ongoing.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Phase.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Waiting.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
=> Implement game phases

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeTeam.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
Methods to move players arround the prison
=> ﻿Prison teleports implemented

src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitInventory.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeItem.java
=> Update convert items to have the correct materials

src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java, src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java, src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeSubcommandExecutor.java, src/main/java/net/tiagofar78/prisonescape/commands/StartSubcommand.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/java/net/tiagofar78/prisonescape/managers/GameManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Implemented a command that allows the game to be started. I also added a base for commands execution and a GameManager,
=> Implemented start game command

src/main/java/net/tiagofar78/prisonescape/commands/ForceStartSucommand.java, src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Implemented force start command that allows the game to be skiped to ongoing phase.
=> Implemented force start command

src/main/java/net/tiagofar78/prisonescape/commands/ForceStartSubcommand.java, src/main/java/net/tiagofar78/prisonescape/commands/JoinSubcommand.java, src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Also fixed some typos.
Closes #22
=> Implement join command

src/main/java/net/tiagofar78/prisonescape/commands/LeaveSubcommand.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Implemented leave command and fixed some small problems in join command.
=> Implemented leave command

src/main/java/net/tiagofar78/prisonescape/commands/ForceStopSubcommand.java, src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
=> Add base for force stop command

src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMessageSender.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Implemented waiting phase logic with announcements and a scheduler.
=> Implement waiting phase

src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java, src/main/java/net/tiagofar78/prisonescape/commands/RejoinSubcommand.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeTeam.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
=> Add rejoin command

src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java, src/main/java/net/tiagofar78/prisonescape/commands/StopSubcommand.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Finished.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Ongoing.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Phase.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Waiting.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/resources/languages/english.yml
=> Implement Stop command

src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeItem.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java, src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/resources/languages/english.yml
Now it is possible to select your prefered team to play in.
=> Implemented team selector kit

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Finished.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Ongoing.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Waiting.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/resources/languages/english.yml
Fixed some bugs and now it is possible for prisioners to escape and win the game. It is already possible for police team to win the game if the prisioners can't escape.
=> Small bugs fixed

src/main/java/net/tiagofar78/prisonescape/Events.java, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitItems.java, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java, src/main/java/net/tiagofar78/prisonescape/game/MenuType.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/resources/config.yml, src/main/resources/languages/english.yml
This PR will add the vaults feature completely.
=> Vault inteligence

src/main/java/net/tiagofar78/prisonescape/Events.java
=> Assert there is no rain

.github/workflows/compile-and-check-format.yml
Pipeline to check if code compiles and if formatting is up to code standards
Closes #93
=> Add pipeline

.github/ISSUE_TEMPLATE/bug--bug-report.md, .github/ISSUE_TEMPLATE/enh--feature-request.md
=> Add issue templates

README.md
Just added a thank you for contributions and how to get assigned an issue
=> Update contributing section on readme.md

src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
=> World time is now consistent with game time

formatter-config.xml, src/main/java/net/tiagofar78/prisonescape/Events.java, src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java
Now annotations stay in seperate lines
=> Fix formatter

src/main/java/net/tiagofar78/prisonescape/Events.java
=> Players do not lose health anymore

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/kits/PrisionerKit.java
=> added PrisionerKit

README.md
Added a building section to read.me file with some info on how to compile the plugin.
=> Building section on READ.ME

src/main/java/net/tiagofar78/prisonescape/Events.java, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Clickable.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
Now every click in a player inventory are working fine.
=> Player Inventory Clicks

src/main/java/net/tiagofar78/prisonescape/Events.java
=> Created variable for player

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
This PR is the first step in order to complete issue #57 , it will add movement using secret passages so that prisioners can go underground and police don't.
=> Secret Passages Movement

src/main/java/net/tiagofar78/prisonescape/Events.java
Block mob spawning in the prison escape world
=> Fix mob spawning in prison

src/main/java/net/tiagofar78/prisonescape/Events.java
=> Add restriction so players cannot build

src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitItems.java, src/main/java/net/tiagofar78/prisonescape/items/MetalShovelItem.java, src/main/java/net/tiagofar78/prisonescape/items/MetalSpoonItem.java, src/main/java/net/tiagofar78/prisonescape/items/PlasticShovelItem.java, src/main/java/net/tiagofar78/prisonescape/items/PlasticSpoonItem.java, src/main/java/net/tiagofar78/prisonescape/items/WrenchItem.java
=> Remove minecraft attributes from tools lore

src/main/java/net/tiagofar78/prisonescape/Events.java
=> Assert player cannot drop glass pane

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
=> Implement hasIllegalItems and hasMetalItems

src/main/java/net/tiagofar78/prisonescape/Events.java, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java, src/main/java/net/tiagofar78/prisonescape/dataobjects/ItemProbability.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java, src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java, src/main/java/net/tiagofar78/prisonescape/items/ToolItem.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
This PR will take care of items durability. The durability will be displayed in name and with minecraft durability properties.
=> Tool items durability

.gitignore, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/ClickDoorReturnAction.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CodeDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/Door.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GoldenDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GrayDoor.java, src/main/java/net/tiagofar78/prisonescape/items/DoorCodeItem.java, src/main/java/net/tiagofar78/prisonescape/items/GoldenKeyItem.java, src/main/java/net/tiagofar78/prisonescape/items/GrayKeyItem.java, src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/resources/config.yml, src/main/resources/languages/english.yml
=> Implement doors

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java, src/main/java/net/tiagofar78/prisonescape/kits/Kit.java, src/main/java/net/tiagofar78/prisonescape/kits/PoliceKit.java, src/main/java/net/tiagofar78/prisonescape/kits/PrisionerKit.java, src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java
This PR will fix the bug where functional items don't do anything when clicked.
=> Item not detecting interactions

src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
=> Fix players not teleporting at beginning of game

TestServer/plugins/TF_PrisonEscape/config.yml
=> Chests contents

TestServer/plugins/TF_PrisonEscape/config.yml, TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/game/Guard.java, src/main/java/net/tiagofar78/prisonescape/game/Prisioner.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeTeam.java, src/main/java/net/tiagofar78/prisonescape/game/ScoreboardData.java, src/main/java/net/tiagofar78/prisonescape/game/WaitingPlayer.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Helicopter.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CodeDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GoldenDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GrayDoor.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/menus/Shop.java, src/main/resources/languages/english.yml
This PR will focus on adding a scoreboard to players who should have one. An abstraction will be created in order to make updates to the scoreboard easy to do.
=> Player scoreboard

TestServer/plugins/TF_PrisonEscape/config.yml, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/SoundDetector.java
=> Sound detector particles

src/main/java/net/tiagofar78/prisonescape/game/Guard.java
=> Fixed bug where starting balance was being shown as 0 on scoreboard

TestServer/plugins/TF_PrisonEscape/config.yml, src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CellDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/Door.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/resources/config.yml
=> Cell Doors

README.md, TestServer/README.md
=> Add Test server instructions

src/main/java/net/tiagofar78/prisonescape/Events.java
=> Fixed bug where phisical interactions were triggering items

TestServer/plugins/TF_PrisonEscape/config.yml, src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/resources/config.yml
=> Teleport after escaping

src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vent.java
=> TrapDoors spawning on upper half of block

src/main/java/net/tiagofar78/prisonescape/game/Guard.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/SoundDetector.java
=> Sound Detector Animation

TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/Events.java, src/main/java/net/tiagofar78/prisonescape/game/PEGame.java, src/main/java/net/tiagofar78/prisonescape/game/PEPlayer.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Disabled.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Finished.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Ongoing.java, src/main/java/net/tiagofar78/prisonescape/game/phases/Phase.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CellDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CodeDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/Door.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GoldenDoor.java, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GrayDoor.java, src/main/java/net/tiagofar78/prisonescape/items/BombItem.java, src/main/java/net/tiagofar78/prisonescape/items/GoldenKeyItem.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/menus/Clickable.java, src/main/java/net/tiagofar78/prisonescape/menus/CraftingMenu.java, src/main/java/net/tiagofar78/prisonescape/menus/Shop.java, src/main/java/net/tiagofar78/prisonescape/menus/TradeMenu.java, src/main/resources/languages/english.yml
=> Fix vaults disappearing items

src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
=> Fix bars not connecting

TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/placeables/Camera.java, src/main/java/net/tiagofar78/prisonescape/items/OpenCamerasItem.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/resources/languages/english.yml
Partially fixes #280, there is still a bug where players can sometimes teleport to cameras. When issue #174 is solved this bug will be solved as well.
=> Fixed bug where players in cameras could use gm 3

TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/game/PEGame.java, src/main/java/net/tiagofar78/prisonescape/items/TradeItem.java, src/main/java/net/tiagofar78/prisonescape/kits/PrisonerKit.java, src/main/java/net/tiagofar78/prisonescape/listener/PlayerListener.java, src/main/resources/languages/english.yml
=> Trade item

TestServer/plugins/TF_PrisonEscape/config.yml, TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/game/Guard.java, src/main/java/net/tiagofar78/prisonescape/game/PEGame.java, src/main/java/net/tiagofar78/prisonescape/items/MissionsItem.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/missions/ColorConnectMission.java, src/main/java/net/tiagofar78/prisonescape/missions/Mission.java, src/main/resources/config.yml, src/main/resources/languages/english.yml
=> Color Connect Mission

TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/missions/Mission.java, src/main/java/net/tiagofar78/prisonescape/missions/RicochetMission.java, src/main/resources/languages/english.yml
=> Ricochet Mission

TestServer/plugins/TF_PrisonEscape/config.yml, TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/game/PEPlayer.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/missions/DifferencesMission.java, src/main/java/net/tiagofar78/prisonescape/missions/Mission.java, src/main/resources/config.yml, src/main/resources/languages/english.yml
=> Differences Mission

TestServer/plugins/TF_PrisonEscape/languages/english.yml, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/missions/Mission.java, src/main/java/net/tiagofar78/prisonescape/missions/SortMission.java, src/main/resources/languages/english.yml
=> Sort Mission

TestServer/plugins/TF_PrisonEscape/languages/english.yml, pom.xml, src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java, src/main/java/net/tiagofar78/prisonescape/menus/Shop.java, src/main/resources/languages/english.yml
=> Shop Prices

src/main/java/net/tiagofar78/prisonescape/game/PEGame.java, src/main/java/net/tiagofar78/prisonescape/items/Item.java, src/main/java/net/tiagofar78/prisonescape/items/SelectNoneTeamItem.java, src/main/java/net/tiagofar78/prisonescape/items/SelectPoliceTeamItem.java, src/main/java/net/tiagofar78/prisonescape/items/SelectPrisonerTeamItem.java, src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java
=> Enchant items on select team

src/main/java/net/tiagofar78/prisonescape/game/PEGame.java, src/main/java/net/tiagofar78/prisonescape/game/PEPlayer.java, src/main/java/net/tiagofar78/prisonescape/game/phases/DisabledPhase.java, src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
=> Fix boss bar language

TestServer/plugins/TF_PrisonEscape/config.yml, src/main/java/net/tiagofar78/prisonescape/kits/Kit.java
Fixed Bug with underground doors locations.
Fixed Bug with prisoners Inventory
=> Fixed Small Bugs

TestServer/plugins/TF_PrisonEscape/config.yml
=> Fix wrong secret passage config
